### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by KenanK0**
> Let's keep pushing

### CODE REVIEW

**Review by iam-hbk — COMMENTED** [review]
Chaleur 🔥🚀

**Review by iam-hbk — COMMENTED** [review]
image

not sure if it's a theming problem but multiple parts of the website have an inverted color
like the one shown in the picture
image
Also in form at the footer 
image

**Comment by KenanK0** [comment]
fixed #2  and home page v1 is also there

**Review by iam-hbk — APPROVED** [review]
sharp

**Pull request merged**
